# Revo Norm - Text Normalizer for TTS

This notebook provides an interactive testing environment for the Revo Norm text normalization library.

## Features
- English and Malay (Bahasa Melayu) normalization
- Numbers, currency, dates, time, temperature
- Abbreviations, acronyms, elongated words
- Malaysian-specific features (IC numbers, Hijri years, measurements)
- Code-mixing support

In [1]:
# Install and import the library
import sys
sys.path.insert(0, '..')

from revo_norm import (
    normalize_text,
    standard_config,
    basic_config,
    aggressive_config,
    minimal_config,
    FeatureGroup,
    FeatureLevel,
    NormalizationConfig,
    to_cardinal,
    to_currency,
    to_ordinal,
    to_year,
    EntityExtractor,
    EntityType
)

import pandas as pd
from IPython.display import display, HTML

print("Revo Norm library loaded successfully!")
print("\nAvailable configs:")
print("- minimal_config: Basic cleanup only")
print("- basic_config: Standard normalization for conversations")
print("- standard_config: Full normalization (default)")
print("- aggressive_config: Maximum normalization for social media")

Revo Norm library loaded successfully!

Available configs:
- minimal_config: Basic cleanup only
- basic_config: Standard normalization for conversations
- standard_config: Full normalization (default)
- aggressive_config: Maximum normalization for social media

## Quick Test Function

This helper function makes it easy to test multiple sentences at once.

In [2]:
def test_normalize(text, language="ms", config=None, extract_entities=False):
    """Test normalization and display results."""
    result = normalize_text(
        text,
        language=language,
        config=config,
        extract_entities_first=extract_entities
    )
    
    print(f"Input ({language.upper()}):  {text}")
    print(f"Output:              {result}")
    print()
    return result

def test_batch(test_cases, language="ms"):
    """Test multiple cases and display as a table."""
    results = []
    for input_text in test_cases:
        output = normalize_text(input_text, language=language)
        results.append({"Input": input_text, "Output": output})
    
    df = pd.DataFrame(results)
    display(HTML(df.to_html(index=False)))
    return results

def compare_configs(text, language="ms"):
    """Compare different configuration profiles."""
    configs = {
        "minimal": minimal_config(),
        "basic": basic_config(),
        "standard": standard_config(),
        "aggressive": aggressive_config()
    }
    
    print(f"Input: {text}\n")
    for name, config in configs.items():
        result = normalize_text(text, language=language, config=config)
        print(f"[{name.upper()}] {result}")
    print()

print("Test functions loaded!")

Test functions loaded!

---

# 1. NUMBERS & CURRENCY (Nombor & Mata Wang)

Test basic number and currency normalization.

In [3]:
# Test basic numbers
test_normalize("Saya ada 5 kucing", language="ms")

# Test currency
test_normalize("Harga RM15", language="ms")
test_normalize("Gaji RM 3,000", language="ms")
test_normalize("Pinjaman RM 300K", language="ms")

# Test percentages
test_normalize("100% kecekapan", language="ms")
test_normalize("Diskaun 50%", language="ms")

Input (MS):  Saya ada 5 kucing
Output:              Saya ada lima kucing

Input (MS):  Harga RM15
Output:              Harga lima belas ringgit

Input (MS):  Gaji RM 3,000
Output:              Gaji tiga ribu ringgit

Input (MS):  Pinjaman RM 300K
Output:              Pinjaman tiga ratus ribu ringgit

Input (MS):  100% kecekapan
Output:              seratus peratus kecekapan

Input (MS):  Diskaun 50%
Output:              Diskaun lima puluh peratus

'Diskaun lima puluh peratus'

### Batch Test: Currency

In [4]:
currency_tests = [
    "RM50",
    "RM 1,200",
    "RM30K",
    "RM 4.5 juta",
    "50 sen",
    "RM30.59",
    "RM 3.50"
]

test_batch(currency_tests, language="ms")

[{'Input': 'RM50', 'Output': 'lima puluh ringgit'},
 {'Input': 'RM 1,200', 'Output': 'seribu dua ratus ringgit'},
 {'Input': 'RM30K', 'Output': 'tiga puluh ribu ringgit'},
 {'Input': 'RM 4.5 juta', 'Output': 'empat perpuluhan lima juta ringgit'},
 {'Input': '50 sen', 'Output': 'lima puluh sen'},
 {'Input': 'RM30.59', 'Output': 'tiga puluh ringgit lima puluh sembilan sen'},
 {'Input': 'RM 3.50', 'Output': 'tiga ringgit lima puluh sen'}]

In [39]:
from revo_norm import normalize_text

malaysian_acronyms = [
    # Government & Agencies
    "MARA",        # Majlis Amanah Rakyat
    "JAKIM",       # Jabatan Kemajuan Islam Malaysia
    "FELDA",       # Federal Land Development Authority
    "PERHILITAN",  # Jabatan Perlindungan Hidupan Liar dan Taman Negara
    "BERNAMA",     # Berita Nasional Malaysia
    "FINAS",       # Perbadanan Kemajuan Filem Nasional Malaysia
    
    # Infrastructure & Corporate
    "PLUS",        # Projek Lebuhraya Utara Selatan
    "RAPID",       # Rangkaian Pengangkutan Integrasi Deras
    "PETRONAS",    # Petroliam Nasional Berhad
    "BERNAS", 
         "PTPTN",     # Padiberas Nasional Berhad
    
    # Common Nouns (Portmanteaus)
    "Tadika",      # Taman Didikan Kanak-kanak
    "Taska",       # Taman Asuhan Kanak-kanak
    "Pawagam",     # Panggung Wayang Gambar
    "Cerpen",      # Cerita Pendek
    "Kugiran",     # Kumpulan Gitar Rancak
    
    # Education
    "UPSI",        # Universiti Pendidikan Sultan Idris
    "UITM"         # Universiti Teknologi MARA
]
from revo_norm import normalize_text
for x in malaysian_acronyms:
    print(f"{x} -> {normalize_text(x, language='ms')}")

MARA -> mara
JAKIM -> jakim
FELDA -> felda
PERHILITAN -> perhilitan
BERNAMA -> bernama
FINAS -> finas
PLUS -> P lus
RAPID -> rapid
PETRONAS -> petronas
BERNAS -> bernas
PTPTN -> P T P T N
Tadika -> Tadika
Taska -> Taska
Pawagam -> Pawagam
Cerpen -> Cerpen
Kugiran -> Kugiran
UPSI -> upsi
UITM -> U I T M

In [34]:
currency_tests = [
    "RM50",
    "RM 1,200",
    "RM30K",
    "RM 4.5 million",
    "50 sen",
    "RM30.59",
    "RM 3.50",
    "Hari ini I need to go to Putrajaya at 4pm. Parking fee RM50 je. Tapi kat KL, parking charges RM30.59. I ingat nak pergi but then hujan, so nevermind lah. Mana saya boleh beli air? I need some fresh air."
]

test_batch(currency_tests, language="en")

[{'Input': 'RM50', 'Output': 'fifty ringgit'},
 {'Input': 'RM 1,200', 'Output': 'one thousand, two hundred ringgit'},
 {'Input': 'RM30K', 'Output': 'thirty thousand ringgit'},
 {'Input': 'RM 4.5 million', 'Output': 'four point five million ringgit'},
 {'Input': '50 sen', 'Output': 'fifty sen'},
 {'Input': 'RM30.59', 'Output': 'thirty ringgit fifty nine cent'},
 {'Input': 'RM 3.50', 'Output': 'three ringgit fifty cent'},
 {'Input': 'Hari ini I need to go to Putrajaya at 4pm. Parking fee RM50 je. Tapi kat KL, parking charges RM30.59. I ingat nak pergi but then hujan, so nevermind lah. Mana saya boleh beli air? I need some fresh air.',
  'Output': 'Hari ini I need to go to Putrajaya at four P M. Parking fee fifty ringgit je. Tapi kat K L, parking charges thirty ringgit fifty nine cent. I ingat nak pergi but then hujan, so nevermind lah. Mana saya boleh beli air? I need some fresh air.'}]

---

# 2. DATES & TIME (Tarikh & Masa)

Test date and time normalization.

In [7]:
# Test dates
test_normalize("15/08/2025", language="ms")
test_normalize("2025-08-15", language="ms")
test_normalize("15 Ogos 2025", language="ms")

# Test time
test_normalize("pukul 3:30", language="ms")
test_normalize("jam 9:45 pagi", language="ms")
test_normalize("12:00 tengahari", language="ms")
test_normalize("5:15 petang", language="ms")

Input (MS):  15/08/2025
Output:              lima belas Ogos dua ribu dua puluh lima

Input (MS):  2025-08-15
Output:              dua kosong dua lima kosong lapan satu lima

Input (MS):  15 Ogos 2025
Output:              lima belas Ogos dua ribu dua puluh lima

Input (MS):  pukul 3:30
Output:              pukul tiga tiga puluh

Input (MS):  jam 9:45 pagi
Output:              jam sembilan empat puluh lima pagi

Input (MS):  12:00 tengahari
Output:              tengah hari tengahari

Input (MS):  5:15 petang
Output:              lima lima belas petang

'lima lima belas petang'

---

# 3. TEMPERATURE & MEASUREMENTS (Suhu & Ukuran)

Test temperature and measurement normalization.

In [8]:
# Test temperature
test_normalize("25°C", language="ms")
test_normalize("suhu 30C", language="ms")
test_normalize("Minus 5 darjah", language="ms")

# Test measurements
test_normalize("5km", language="ms")
test_normalize("100kg", language="ms")
test_normalize("2.5 meter", language="ms")
test_normalize("50 liter", language="ms")

Input (MS):  25°C
Output:              dua puluh lima°C

Input (MS):  suhu 30C
Output:              suhu tiga puluh celcius

Input (MS):  Minus 5 darjah
Output:              Minus lima darjah

Input (MS):  5km
Output:              lima kilometer

Input (MS):  100kg
Output:              seratus kilogram

Input (MS):  2.5 meter
Output:              dua perpuluhan lima meter

Input (MS):  50 liter
Output:              lima puluh liter

'lima puluh liter'

---

# 4. IC NUMBERS & PHONE (No. KP & Telefon)

Test Malaysian IC numbers and phone numbers.

In [9]:
# Test IC numbers
test_normalize("IC 123456-78-9012", language="ms")
test_normalize("No KP: 850101-01-5555", language="ms")

# Test phone numbers
test_normalize("012-3456789", language="ms")
test_normalize("+60123456789", language="ms")
test_normalize("03-80001234", language="ms")

Input (MS):  IC 123456-78-9012
Output:              I C satu dua tiga empat lima enam tujuh lapan sembilan kosong satu dua

Input (MS):  No KP: 850101-01-5555
Output:              No K P: lapan lima kosong satu kosong satu kosong satu lima lima lima, lima

Input (MS):  012-3456789
Output:              kosong satu dua tiga empat lima enam tujuh lapan sembilan

Input (MS):  +60123456789
Output:              plus enam kosong satu dua tiga empat lima enam tujuh lapan sembilan

Input (MS):  03-80001234
Output:              kosong tiga lapan kosong kosong kosong satu dua tiga empat

'kosong tiga lapan kosong kosong kosong satu dua tiga empat'

---

# 5. FRACTIONS & X-KALI (Pecahan & X-Kali)

Test fraction and repetition normalization.

In [10]:
# Test fractions
test_normalize("1/2", language="ms")
test_normalize("3/4", language="ms")
test_normalize("1/4", language="ms")
test_normalize("2/3", language="ms")

# Test x-kali
test_normalize("2 kali", language="ms")
test_normalize("3x", language="ms")
test_normalize("5x ganda", language="ms")

Input (MS):  1/2
Output:              satu per dua

Input (MS):  3/4
Output:              tiga per empat

Input (MS):  1/4
Output:              satu per empat

Input (MS):  2/3
Output:              dua per tiga

Input (MS):  2 kali
Output:              dua kali

Input (MS):  3x
Output:              tiga kali

Input (MS):  5x ganda
Output:              lima kali ganda

'lima kali ganda'

---

# 6. ISLAMIC CALENDAR (Takwim Hijri)

Test Hijri year and hari bulan normalization.

In [11]:
# Test hari bulan
test_normalize("10 haribulan", language="ms")
test_normalize("1 haribulan", language="ms")

# Test Hijri years
test_normalize("tahun 1446H", language="ms")
test_normalize("1 Syawal 1446H", language="ms")

Input (MS):  10 haribulan
Output:              sepuluh haribulan

Input (MS):  1 haribulan
Output:              satu haribulan

Input (MS):  tahun 1446H
Output:              tahun satu empat empat enam Hijri

Input (MS):  1 Syawal 1446H
Output:              satu Syawal satu empat empat enam Hijri

'satu Syawal satu empat empat enam Hijri'

---

# 7. ABBREVIATIONS & ACRONYMS (Singkatan & Akronim)

Test abbreviation and acronym normalization.

In [12]:
# Test abbreviations
test_normalize("dr.", language="ms")
test_normalize("en.", language="ms")
test_normalize("pn.", language="ms")

# Test informal abbreviations
test_normalize("Jalan dgn kaki", language="ms")
test_normalize("Hadiah utk awak", language="ms")
test_normalize("Datang pd pukul 5", language="ms")

# Test acronyms
test_normalize("RTM", language="ms")
test_normalize("TV3", language="ms")
test_normalize("LRT", language="ms")

Input (MS):  dr.
Output:              Doktor.

Input (MS):  en.
Output:              en.

Input (MS):  pn.
Output:              pn.

Input (MS):  Jalan dgn kaki
Output:              Jalan dgn kaki

Input (MS):  Hadiah utk awak
Output:              Hadiah utk awak

Input (MS):  Datang pd pukul 5
Output:              Datang pd pukul lima

Input (MS):  RTM
Output:              R T M

Input (MS):  TV3
Output:              T V tiga

Input (MS):  LRT
Output:              L R T

'L R T'

---

# 8. CODE-MIXING (Kod Campur)

Test English-Malay code mixing common in Malaysia.

In [30]:
# Test code-mixing
test_normalize("Saya nak upload file tu", language="ms")
test_normalize("Deadline esok", language="ms")
test_normalize("Team kami ada 5 ahli", language="ms")
test_normalize("Check email anda aisyahrazak@gmail.com", language="ms")
test_normalize("Backup data harap", language="ms")

Input (MS):  Saya nak upload file tu
Output:              Saya nak upload file tu

Input (MS):  Deadline esok
Output:              Deadline esok

Input (MS):  Team kami ada 5 ahli
Output:              Team kami ada lima ahli

Input (MS):  Check email anda aisyahrazak@gmail.com
Output:              Check email anda aisyahrazak at gmail dot com

Input (MS):  Backup data harap
Output:              Backup data harap

'Backup data harap'

---

# 9. ELONGATED WORDS (Kata Ganda)

Test elongated word normalization.

In [14]:
# Test elongated words
test_normalize("Sayaaa nak pergi", language="ms")
test_normalize("Tidaaaak mau", language="ms")
test_normalize("Sangaaaat baikkkk", language="ms")
test_normalize("Yaaa betul", language="ms")

Input (MS):  Sayaaa nak pergi
Output:              Sayaa nak pergi

Input (MS):  Tidaaaak mau
Output:              Tidaak mau

Input (MS):  Sangaaaat baikkkk
Output:              Sangaat baikk

Input (MS):  Yaaa betul
Output:              Yaa betul

'Yaa betul'

---

# 10. REAL-WORLD SENTENCES (Ayat Sebenar)

Test realistic sentences from various contexts.

In [15]:
# News & Announcements
test_normalize("Kerajaan umumkan RM 15 juta untuk pembangunan sekolah.", language="ms")
test_normalize("Suhu di Kuala Lumpur mencapai 35°C hari ini.", language="ms")

# Transactions
test_normalize("Harga petrol naik 25 sen mulai esok.", language="ms")
test_normalize("Gaji pokok RM 3,000 akan dikreditkan pada 25 haribulan.", language="ms")

# Instructions
test_normalize("Sila hubungi 03-12345678 untuk sebarang pertanyaan.", language="ms")
test_normalize("Puan Rosnah akan menyerahkan dokumen pada pukul 3:30 petang.", language="ms")

Input (MS):  Kerajaan umumkan RM 15 juta untuk pembangunan sekolah.
Output:              Kerajaan umumkan lima belas juta ringgit untuk pembangunan sekolah.

Input (MS):  Suhu di Kuala Lumpur mencapai 35°C hari ini.
Output:              Suhu di Kuala Lumpur mencapai tiga puluh lima°C hari ini.

Input (MS):  Harga petrol naik 25 sen mulai esok.
Output:              Harga petrol naik dua puluh lima sen mulai esok.

Input (MS):  Gaji pokok RM 3,000 akan dikreditkan pada 25 haribulan.
Output:              Gaji pokok tiga ribu ringgit akan dikreditkan pada dua puluh lima haribulan.

Input (MS):  Sila hubungi 03-12345678 untuk sebarang pertanyaan.
Output:              Sila hubungi kosong tiga satu dua tiga empat lima enam tujuh lapan untuk sebarang pertanyaan.

Input (MS):  Puan Rosnah akan menyerahkan dokumen pada pukul 3:30 petang.
Output:              Puan Rosnah akan menyerahkan dokumen pada pukul tiga tiga puluh petang.

'Puan Rosnah akan menyerahkan dokumen pada pukul tiga tiga puluh petang.'

---

# 11. SOCIAL MEDIA & SMS (Media Sosial)

Test informal social media and SMS text.

In [16]:
# SMS style
test_normalize("Ok, sy akn dtg pukul 5 ptg.", language="ms")
test_normalize("Xpwah ah, da lambat la tu.", language="ms")
test_normalize("Tq sbb tlg sy document tu.", language="ms")

# Social media
test_normalize("Video tu dah 1M views dalam masa 24 jam!", language="ms")
test_normalize("Follow IG kami @sukandewan untuk update terkini.", language="ms")
test_normalize("Best gila movie tadi, 5 stars!", language="ms")

Input (MS):  Ok, sy akn dtg pukul 5 ptg.
Output:              Ok, sy akn dtg pukul lima ptg.

Input (MS):  Xpwah ah, da lambat la tu.
Output:              Xpwah ah, da lambat la tu.

Input (MS):  Tq sbb tlg sy document tu.
Output:              Tq sbb tlg sy document tu.

Input (MS):  Video tu dah 1M views dalam masa 24 jam!
Output:              Video tu dah satu meter views dalam masa dua puluh empat jam!

Input (MS):  Follow IG kami @sukandewan untuk update terkini.
Output:              Follow I G kami at sukandewan untuk update terkini.

Input (MS):  Best gila movie tadi, 5 stars!
Output:              Best gila movie tadi, lima stars!

'Best gila movie tadi, lima stars!'

---

# 12. GOVERNMENT FORMS (Borang Kerajaan)

Test government form terminology.

In [ ]:
# Government form fields
test_normalize("No. KP: 850101-01-5555", language="ms")
test_normalize("No. Pasport: A12345678", language="ms")
test_normalize("Pendapatan tahunan: RM 36,000", language="ms")
test_normalize("Jumlah tanggungan: 4 orang", language="ms")
test_normalize("Poskod: 50000", language="ms")

Input (MS):  No. KP: 850101-01-5555
Output:              No. K P: lapan lima kosong satu kosong satu kosong satu lima lima lima, lima

Input (MS):  No. Pasport: A12345678
Output:              No. Pasport: A satu dua tiga empat lima enam tujuh lapan

Input (MS):  Pendapatan tahunan: RM 36,000
Output:              Pendapatan tahunan: tiga puluh enam ribu ringgit

Input (MS):  Jumlah tanggungan: 4 orang
Output:              Jumlah tanggungan: empat orang

Input (MS):  Poskod: 50000
Output:              Poskod: lima kosong kosong kosong, kosong

'Poskod: lima kosong kosong kosong, kosong'

---

# 13. BANKING & FINANCE (Perbankan)

Test banking terminology.

In [18]:
# Banking terms
test_normalize("No. Akaun: 1234567890", language="ms")
test_normalize("Baki akaun: RM 1,250.50", language="ms")
test_normalize("Kadar faedah: 4.5% setahun", language="ms")
test_normalize("Tempoh simpanan: 12 bulan", language="ms")
test_normalize("Had pengeluaran ATM: RM 3,000 sehari", language="ms")

Input (MS):  No. Akaun: 1234567890
Output:              No. Akaun: satu dua tiga empat lima enam tujuh lapan sembilan kosong

Input (MS):  Baki akaun: RM 1,250.50
Output:              Baki akaun: seribu dua ratus lima puluh ringgit lima puluh sen

Input (MS):  Kadar faedah: 4.5% setahun
Output:              Kadar faedah: empat perpuluhan lima peratus setahun

Input (MS):  Tempoh simpanan: 12 bulan
Output:              Tempoh simpanan: dua belas bulan

Input (MS):  Had pengeluaran ATM: RM 3,000 sehari
Output:              Had pengeluaran A T M: tiga ribu ringgit sehari

'Had pengeluaran A T M: tiga ribu ringgit sehari'

---

# 14. EDUCATION (Pendidikan)

Test education terminology.

In [38]:
# Education terms
test_normalize("No. Matrik: A123456", language="ms")
test_normalize("3.75", language="en")
test_normalize("Jam kredit: 3 jam", language="ms")
test_normalize("Kod kursus: CS101", language="ms")
test_normalize("Dewan peperiksaan: Bilik 3", language="ms")

Input (MS):  No. Matrik: A123456
Output:              No. Matrik: A satu dua tiga empat lima enam

Input (EN):  3.75
Output:              three seventy five

Input (MS):  Jam kredit: 3 jam
Output:              Jam kredit: tiga jam

Input (MS):  Kod kursus: CS101
Output:              Kod kursus: C S satu kosong satu

Input (MS):  Dewan peperiksaan: Bilik 3
Output:              Dewan peperiksaan: Bilik tiga

'Dewan peperiksaan: Bilik tiga'

---

# 15. HEALTH & MEDICAL (Kesihatan)

Test health and medical terminology.

In [20]:
# Medical terms
test_normalize("Ambil 2 tablet selepas makan, 3 kali sehari.", language="ms")
test_normalize("Berat badan pesakit ialah 75kg dan tinggi 1.75m.", language="ms")
test_normalize("Tekanan darah normal ialah 120/80.", language="ms")
test_normalize("Suhu badan 37.5°C dianggap demam.", language="ms")

Input (MS):  Ambil 2 tablet selepas makan, 3 kali sehari.
Output:              Ambil dua tablet selepas makan, tiga kali sehari.

Input (MS):  Berat badan pesakit ialah 75kg dan tinggi 1.75m.
Output:              Berat badan pesakit ialah tujuh puluh lima kilogram dan tinggi satu tujuh puluh lima meter.

Input (MS):  Tekanan darah normal ialah 120/80.
Output:              Tekanan darah normal ialah seratus dua puluh per lapan puluh.

Input (MS):  Suhu badan 37.5°C dianggap demam.
Output:              Suhu badan tiga puluh tujuh perpuluhan lima°C dianggap demam.

'Suhu badan tiga puluh tujuh perpuluhan lima°C dianggap demam.'

---

# 16. TRANSPORTATION (Pengangkutan)

Test transport terminology.

In [21]:
# Transport terms
test_normalize("Perjalanan mengambil masa 2 jam 30 minit.", language="ms")
test_normalize("Jarak dari KL ke Ipoh lebih kurang 200km.", language="ms")
test_normalize("Kereta ekspres bertolak pada 10:45 pagi.", language="ms")
test_normalize("Had laju di lebuhraya ialah 110km/j.", language="ms")

Input (MS):  Perjalanan mengambil masa 2 jam 30 minit.
Output:              Perjalanan mengambil masa dua jam tiga puluh minit.

Input (MS):  Jarak dari KL ke Ipoh lebih kurang 200km.
Output:              Jarak dari K L ke Ipoh lebih kurang dua ratus kilometer.

Input (MS):  Kereta ekspres bertolak pada 10:45 pagi.
Output:              Kereta ekspres bertolak pada sepuluh empat puluh lima pagi.

Input (MS):  Had laju di lebuhraya ialah 110km/j.
Output:              Had laju di lebuhraya ialah seratus sepuluh kilometer/j.

'Had laju di lebuhraya ialah seratus sepuluh kilometer/j.'

---

# 17. FOOD & RECIPES (Makanan & Resepi)

Test food and recipe terminology.

In [22]:
# Recipe measurements
test_normalize("Tambah 1 sudu makan gula dan 2 sudu teh garam.", language="ms")
test_normalize("Masak selama 20 minit dengan api sederhana.", language="ms")
test_normalize("Panaskan oven pada suhu 180°C selama 15 minit.", language="ms")
test_normalize("Aduk 3/4 cawan tepung dengan 1/2 cawan susu.", language="ms")

Input (MS):  Tambah 1 sudu makan gula dan 2 sudu teh garam.
Output:              Tambah satu sudu makan gula dan dua sudu teh garam.

Input (MS):  Masak selama 20 minit dengan api sederhana.
Output:              Masak selama dua puluh minit dengan api sederhana.

Input (MS):  Panaskan oven pada suhu 180°C selama 15 minit.
Output:              Panaskan oven pada suhu seratus lapan puluh°C selama lima belas minit.

Input (MS):  Aduk 3/4 cawan tepung dengan 1/2 cawan susu.
Output:              Aduk tiga per empat cawan tepung dengan satu per dua cawan susu.

'Aduk tiga per empat cawan tepung dengan satu per dua cawan susu.'

---

# 18. COMPARING CONFIGURATIONS

Compare how different configuration profiles handle the same text.

In [23]:
# Compare configs on informal text
compare_configs("Saya x faham la apa korang cakap ni", language="ms")

compare_configs("Video tu dah 1M views dalam masa 24 jam!", language="ms")

compare_configs("Ok, sy akn dtg pukul 5 ptg.", language="ms")

Input: Saya x faham la apa korang cakap ni

[MINIMAL] Saya x faham la apa korang cakap ni
[BASIC] Saya x faham la apa korang cakap ni
[STANDARD] Saya x faham la apa korang cakap ni
[AGGRESSIVE] Saya x faham la apa korang cakap ni

Input: Video tu dah 1M views dalam masa 24 jam!

[MINIMAL] Video tu dah satu M views dalam masa dua puluh empat jam!
[BASIC] Video tu dah satu meter views dalam masa dua puluh empat jam!
[STANDARD] Video tu dah satu meter views dalam masa dua puluh empat jam!
[AGGRESSIVE] Video tu dah satu meter views dalam masa dua puluh empat jam!

Input: Ok, sy akn dtg pukul 5 ptg.

[MINIMAL] Ok, sy akn dtg pukul lima ptg.
[BASIC] Ok, sy akn dtg pukul lima ptg.
[STANDARD] Ok, sy akn dtg pukul lima ptg.
[AGGRESSIVE] Ok, sy akn dtg pukul lima ptg.

---

# 19. ENTITY EXTRACTION MODE

Test the experimental entity extraction mode (`extract_entities_first=True`).

This mode is useful for preventing pattern conflicts, especially with dates/fractions.

In [24]:
from revo_norm import normalize_text, standard_config, EntityExtractor, EntityType

normalize_text('PERKESO')

'perkeso'

In [25]:
# Test entity extraction mode
# This helps prevent issues like "15/08/2025" being interpreted as a fraction

text1 = "Pertandingan pada 15/08/2025 jam 2:30 petang di PERKESO"
print(f"Input: {text1}\n")
print("[Normal mode]:")
print(normalize_text(text1, language="ms"))
print("\n[Entity extraction mode]:")
print(normalize_text(text1, language="ms", extract_entities_first=True))

print("\n" + "="*60 + "\n")

# Test with currency (prevents "RM" from being split)
text2 = "RM 450000 untuk projek ML"
print(f"Input: {text2}\n")
print("[Normal mode]:")
print(normalize_text(text2, language="ms"))
print("\n[Entity extraction mode]:")
print(normalize_text(text2, language="ms", extract_entities_first=True))

Input: Pertandingan pada 15/08/2025 jam 2:30 petang di PERKESO

[Normal mode]:
Pertandingan pada lima belas Ogos dua ribu dua puluh lima jam dua tiga puluh petang di perkeso

[Entity extraction mode]:
Pertandingan pada lima belas Ogos dua ribu dua puluh lima jam dua tiga puluhpetang di perkeso

============================================================

Input: RM 450000 untuk projek ML

[Normal mode]:
empat ratus lima puluh ribu ringgit untuk projek M L

[Entity extraction mode]:
empat ratus lima puluh ribu ringgit untuk projek M L

---

# 20. CUSTOM CONFIGURATION

Create custom configurations by enabling/disabling specific features.

In [26]:
# Create custom config - disable acronym expansion
custom_config = standard_config()
custom_config.with_feature(FeatureGroup.ACRONYMS, FeatureLevel.OFF)

text = "Doktor dari KKM akan ke KTM"
print(f"Input: {text}\n")
print("[Standard - acronyms expanded]:")
print(normalize_text(text, language="ms", config=standard_config()))
print("\n[Custom - acronyms preserved]:")
print(normalize_text(text, language="ms", config=custom_config))

# Create minimal config - only basic cleanup
minimal = minimal_config()
print("\n[Minimal - basic cleanup only]:")
print(normalize_text(text, language="ms", config=minimal))

Input: Doktor dari KKM akan ke KTM

[Standard - acronyms expanded]:
Doktor dari K K M akan ke K T M

[Custom - acronyms preserved]:
Doktor dari KKM akan ke KTM

[Minimal - basic cleanup only]:
Doktor dari KKM akan ke KTM

---

# 21. DIRECT NUMBER-TO-WORDS CONVERSION

Use the number-to-words functions directly.

In [27]:
# Cardinal numbers
print("Cardinal numbers:")
for num in [0, 1, 5, 10, 15, 20, 25, 100, 1000, 1000000]:
    print(f"  {num} -> {to_cardinal(num)}")

# Currency
print("\nCurrency:")
for amount in [1.50, 15, 100, 1500, 10000]:
    print(f"  RM {amount} -> {to_currency(amount)}")

# Ordinal
print("\nOrdinal:")
for num in [1, 2, 3, 10, 15, 21, 100]:
    print(f"  ke-{num} -> {to_ordinal(num)}")

# Years
print("\nYears:")
for year in [1990, 2000, 2025, 3000]:
    print(f"  {year} -> {to_year(year)}")

Cardinal numbers:
  0 -> kosong
  1 -> satu
  5 -> lima
  10 -> sepuluh
  15 -> lima belas
  20 -> dua puluh
  25 -> dua puluh lima
  100 -> seratus
  1000 -> seribu
  1000000 -> satu juta

Currency:
  RM 1.5 -> satu perpuluhan lima ringgit
  RM 15 -> lima belas ringgit
  RM 100 -> seratus ringgit
  RM 1500 -> seribu lima ratus ringgit
  RM 10000 -> sepuluh ribu ringgit

Ordinal:
  ke-1 -> pertama
  ke-2 -> kedua
  ke-3 -> ketiga
  ke-10 -> kesepuluh
  ke-15 -> kelima belas
  ke-21 -> kedua puluh satu
  ke-100 -> keseratus

Years:
  1990 -> seribu sembilan ratus sembilan puluh
  2000 -> dua ribu
  2025 -> dua ribu dua puluh lima
  3000 -> tiga ribu

---

# 22. INTERACTIVE TEST

Test your own text here!

In [54]:
# Test your own text
my_text = "Email me at john@example.com"
my_language = "ms"  # Change to "en" for English

result = normalize_text(my_text, language=my_language)
print(f"Input:  {my_text}")
print(f"Output: {result}")

Input:  Email me at john@example.com
Output: Email me at john at example dot com

---

## Summary

This notebook covers:
- ✅ Numbers and currency
- ✅ Dates and time
- ✅ Temperature and measurements
- ✅ IC numbers and phone numbers
- ✅ Fractions and x-kali
- ✅ Islamic calendar terms
- ✅ Abbreviations and acronyms
- ✅ Code-mixing (English-Malay)
- ✅ Elongated words
- ✅ Real-world sentences
- ✅ Social media and SMS
- ✅ Government forms
- ✅ Banking and finance
- ✅ Education
- ✅ Health and medical
- ✅ Transportation
- ✅ Food and recipes
- ✅ Configuration comparison
- ✅ Entity extraction mode
- ✅ Custom configuration
- ✅ Direct number-to-words

### Next Steps

1. Run all cells to verify normalization works correctly
2. Add your own test cases in the "Interactive Test" section
3. Use `compare_configs()` to understand different normalization levels
4. Try `extract_entities_first=True` for complex sentences with multiple entities

### Running Tests

```bash
# Run all tests
uv run pytest tests/ -v

# Run Malay tests only
uv run pytest tests/test_malay_normalization.py -v

# Run specific test class
uv run pytest tests/test_malay_normalization.py::TestMalayBeritaDanPengumuman -v
```

In [44]:

# Import required libraries
from revo_norm import normalize_text

# Define comprehensive test cases for English and Malay
test_cases = {
    "english": {
        "name": "English Test Cases",
        "tests": [
            # Numbers and Cardinals
            ("I have 5 apples", "basic cardinal number"),
            ("The price is $1,250.50", "currency with decimals"),
            ("It costs $50", "simple currency"),
            ("2.5 million people", "large numbers"),
            ("The 1st place winner", "ordinal numbers"),
            ("Page 42", "page number"),
            
            # Dates and Times
            ("Meet me on 15/08/2025", "date format DD/MM/YYYY"),
            ("The event is on 2025-08-15", "date format YYYY-MM-DD"),
            ("See you at 3:30 PM", "time with AM/PM"),
            ("The meeting is at 9:00 am", "time lowercase am"),
            ("January 1st, 2025", "written date"),
            
            # Measurements and Units
            ("The temperature is 25°C", "celsius"),
            ("It's 98.6°F", "fahrenheit"),
            ("Weight is 75kg", "kilograms"),
            ("Height is 1.75m", "meters"),
            ("Drive 5km north", "kilometers"),
            ("Add 2.5 liters", "liters"),
            ("500mg dosage", "milligrams"),
            
            # Technology and Acronyms
            ("Download the PDF file", "tech acronym"),
            ("Connect to WiFi", "WiFi"),
            ("The API endpoint", "API acronym"),
            ("CPU usage high", "CPU"),
            ("GPU accelerated", "GPU"),
            ("Train the ML model", "ML"),
            ("AI is the future", "AI"),
            ("Build a GUI interface", "GUI"),
            ("Parse JSON data", "JSON"),
            ("Save as JPEG", "JPEG"),
            ("ASCII character", "ASCII"),
            
            # URLs and Emails
            ("Visit www.google.com", "URL"),
            ("Email me at john@example.com", "email"),
            ("Go to https://example.com/path", "HTTPS URL"),
            ("FTP file at ftp://files.com", "FTP URL"),
            
            # Abbreviations
            ("Dr. Smith is here", "doctor abbreviation"),
            ("Mr. Johnson arrived", "mister abbreviation"),
            ("Ave. of the Americas", "avenue abbreviation"),
            ("approx. 100 people", "approximate abbreviation"),
            
            # Fractions
            ("Add 1/2 cup sugar", "fraction half"),
            ("3/4 of the way", "fraction three quarters"),
            ("One third full", "fraction one third"),
            
            # Percentages
            ("50% discount", "percentage"),
            ("The battery is at 85%", "battery percentage"),
            ("0.5% increase", "decimal percentage"),
            
            # Special Characters
            ("A&B Company", "ampersand"),
            ("1+1=2", "plus and equals"),
            ("Contact #support", "hash symbol"),
            ("5*5=25", "asterisk/multiply"),
            
            # Phone Numbers
            ("Call 555-1234", "phone number"),
            ("Dial 1-800-555-5555", "toll free number"),
            
            # Contractions
            ("I'm going home", "contraction I'm"),
            ("Don't worry", "contraction don't"),
            ("It's raining", "contraction it's"),
            ("We'll meet tomorrow", "contraction we'll"),
            ("They've arrived", "contraction they've"),
            ("He'd like that", "contraction he'd"),
            ("shouldn't do that", "contraction shouldn't"),
            
            # Elongated words (social media style)
            ("Sooooo excited", "elongated word"),
            ("Yesssss I agree", "elongated yes"),
            ("Noooo way", "elongated no"),
            
            # Mixed case and formatting
            ("ALL CAPS TEXT", "all caps"),
            ("Title Case Text", "title case"),
            ("  extra   spaces  ", "extra spaces"),
            
            # Chemical formulas and scientific
            ("H2O is water", "chemical formula"),
            ("CO2 emissions", "carbon dioxide"),
            
            # Time expressions
            ("See you tomorrow", "relative time"),
            ("I'll be there in 5 minutes", "duration"),
            ("Wait 2 hours", "hour duration"),
            
            # Money expressions
            ("It costs 50 cents", "cents"),
            ("€100 for the item", "euros"),
            ("£50 payment", "pounds"),
            
            # Mathematical expressions
            ("The ratio is 3:1", "ratio"),
            ("5>3", "greater than"),
            ("2<5", "less than"),
            
            # Brands and proper nouns
            ("NASA launched a rocket", "NASA"),
            ("IKEA furniture store", "IKEA"),
            
            # Social media elements
            ("@user mention", "at mention"),
            ("#hashtag trend", "hashtag"),
            ("Like and subscribe", "social media verbs"),
            
            # Numbers with suffixes
            ("The 2nd edition", "ordinal suffix"),
            ("3rd place winner", "third ordinal"),
            
            # Temperature extremes
            ("-5°C outside", "negative temperature"),
            ("100°F boiling point", "fahrenheit 100"),
            
            # Multiple entities
            ("On 15/08/2025 at 3:30 PM, the temperature was 25°C", "combined entities"),
            ("Buy 2 items at $50 each for 100% satisfaction", "multiple entities"),
        ]
    },
    "malay": {
        "name": "Malay Test Cases",
        "tests": [
            # Numbers and Cardinals
            ("Saya ada 5 epal", "nombor kardinal asas"),
            ("Harganya RM1,250.50", "mata wang dengan perpuluhan"),
            ("Harga RM50", "mata wang ringkas"),
            ("2.5 juta penduduk", "nombor besar"),
            
            # Dates and Times
            ("Jumpa pada 15/08/2025", "tarikh DD/MM/YYYY"),
            ("Temuduga pada 2025-08-15", "tarikh YYYY-MM-DD"),
            ("Jumpa pada pukul 3:30 petang", "mas"),
            ("Mesyuarat pada 9:00 pagi", "mas pagi"),
            
            # Measurements and Units
            ("Suhu 25°C", "suhu celsius"),
            ("Berat 75kg", "kilogram"),
            ("Tinggi 1.75m", "meter"),
            ("Pandu 5km ke utara", "kilometer"),
            ("Tambah 2.5 liter", "liter"),
            ("Dos 500mg", "miligram"),
            
            # Technology and Code-mixing
            ("Download fail PDF", "teknologi campur kod"),
            ("Connect ke WiFi", "WiFi"),
            ("Endpoint API", "akronim API"),
            ("Penggunaan CPU tinggi", "CPU"),
            ("Train model ML", "ML"),
            ("AI adalah masa depan", "AI"),
            
            # URLs and Emails
            ("Lawati www.google.com", "URL"),
            ("Email saya di ali@example.com", "email"),
            
            # Honorifics and Titles
            ("Dr. Siti ada di sini", "doktor"),
            ("Hj. Ahmad datang", "haji"),
            ("Prof. Tan mengajar", "profesor"),
            ("Datin Lee datang", "datin"),
            
            # Abbreviations and Short forms
            ("Jln ke sana", "jalan disingkat"),
            ("Untuk awak", "untuk"),
            ("Dgn kaki", "dengan"),
            ("Pada pukul 5", "pada"),
            ("Dan lain-lain", "dll"),
            
            # Fractions
            ("Tambah 1/2 cawan gula", "pecahan separuh"),
            ("3/4 perjalanan", "pecahan tiga suku"),
            
            # Percentages
            ("Diskaun 50%", "peratusan"),
            ("Bateri 85%", "peratusan bateri"),
            
            # Elongated words
            ("Sangaaaaat baik", "kata panjangan"),
            ("Yaaa betul", "ya panjangan"),
            
            # Numbers with counters ( classifiers)
            ("2 biji epal", "biji"),
            ("5 orang hadirin", "orang"),
            ("3 ekor kucing", "ekor"),
            ("10 helai kertas", "helai"),
            
            # Islamic terms
            ("Solat Jumaat", "solat"),
            ("Bulan Ramadan", "Ramadan"),
            ("Naik haji", "haji"),
            ("Tahun Hijri 1446", "tahun Hijri"),
            
            # Currency suffixes (Malaysian context)
            ("RM 300K untuk rumah", "currency K suffix"),
            ("Jutaan RM", "juta ringgit"),
            
            # X-kali (multiplier)
            ("10x lebih baik", "10 kali"),
            ("5x ganda", "5 kali"),
            
            # Hari bulan (day of month)
            ("25 haribulan", "25 hari bulan"),
            ("5 haribulan depan", "5 hari bulan"),
            
            # IC numbers
            ("No. KP: 850101-01-5555", "nombor kad pengenalan"),
            
            # Temperature in Malay context
            ("Suhu 35°C hari ini", "suhu tinggi"),
            
            # SMS/Informal style
            ("X faham la", "tak faham"),
            ("Ok, sy akn dtg", "singkatan SMS"),
            ("Mmg tak boleh", "memang tak"),
            ("Np x reply?", "kenapa tak reply"),
            
            # Time expressions
            ("Esok hujan", "esok"),
            ("Sekarang free", "sekarang"),
            ("Kelmarin hujan", "kelmarin"),
            
            # Greetings
            ("Salam sejahtera", "salam"),
            ("Assalamualaikum", "islam greeting"),
            
            # Food and cooking
            ("Masak 20 minit", "masak masa"),
            ("Suhu oven 180°C", "suhu oven"),
            
            # Directions
            ("Ke KL-Putrajaya", "arah"),
            ("Lebuhraya PLUS", "lebuhraya"),
            
            # Government/official
            ("JPJ Putrajaya", "jabatan"),
            ("LRT Masjid Jamek", "lrt"),
            ("MRT Sungai Buloh", "mrt"),
            
            # Ordinal numbers
            ("Tempat ke-1", "pertama"),
            ("Pusingan ke-2", "kedua"),
            ("Ulang tahun ke-10", "kesepuluh"),
            
            # Plural counters
            ("2 buah rumah", "buah"),
            ("5 batang jalan", "batang"),
            
            # Money in sentences
            ("Harga 50 sen", "sen"),
            ("Bayar RM 15 tol", "bayaran tol"),
            
            # Code-mixing tech terms
            ("Save file tu", "save dalam bahasa melayu"),
            ("Upload gambar", "upload"),
            ("Click butang tu", "click"),
            ("Server down", "server down"),
            ("Memory full", "memory penuh"),
            
            # Combined entities
            ("Pada 15/08/2025 jam 3:30 petang, suhu 25°C", "entiti bergabung"),
            ("Beli 2 barang pada RM50 setuju 100% puas hati", "pelbagai entiti"),
            
            # Special characters in Malay
            ("Syarikat A&B", "ampersan"),
            ("No. 5, Jalan 1/2", "alamat pecahan"),
            
            # Social media style
            ("Best gila movie tu", "best gila"),
            ("Xpe ah", "tak apa"),
            ("Follow IG kami", "IG"),
            
            # Measurements with units
            ("100km/j", "kilometer per jam"),
            ("Isi padu 2.5 liter", "isi padu"),
            ("Luas tanah 3.5 hektar", "hektar"),
            
            # Price ranges
            ("Harga RM 10-15", "julat harga"),
            ("Umur 18-25 tahun", "julat umur"),
            
            # Zero and negative
            ("0 markah", "kosong"),
            ("-5°C", "suhu negatif"),
            
            # Years
            ("Tahun 2025", "tahun"),
            ("Abad ke-21", "abad"),
            
            # Large amounts
            ("1,000,000 penduduk", "satu juta"),
            ("Berat 100kg", "berat besar"),
            
            # Islamic calendar
            ("1 Syawal 1446H", "tarikh Hijri"),
            
            # Time duration
            ("Tunggu 2 jam 30 minit", "tempoh masa"),
            
            # Ordinal with words
            ("Minggu depan", "minggu depan"),
            ("Bulan depan", "bulan depan"),
            ("Tahun lepas", "tahun lepas"),
            
            # Common Malay abbreviations
            ("dbpa dpa", "dengan berbagai"),
            ("sprt", "seperti"),
            ("etc", "et cetera"),
            
            # Mixed numbers and text
            ("Kelas 5S1", "kelas"),
            ("No. IC: 123456-01-7890", "IC"),
            
            # Indonesian/Malay differences
            ("Terima kasih", "terima kasih"),
            ("Sama-sama", "sama sama"),
        ]
    }
}

print("Test cases defined successfully!")
print(f"English tests: {len(test_cases['english']['tests'])}")
print(f"Malay tests: {len(test_cases['malay']['tests'])}")

Test cases defined successfully!
English tests: 84
Malay tests: 111